server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://139.196.162.77:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Vxi6uHCARWWSOXWY

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml